name: CI
on: [push, pull_request]
permissions: read-all

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - stable
          - v0.10.4
          - v0.9.5
          - v0.8.3
          - v0.7.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.version }}

      - name: Install Plenary
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

      - name: Run tests
        run: make test
